language: java

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
branches:
  only:
  - master
  - develop
addons:
  sonarcloud:
    organization: valaragen

script:
- mvn clean verify -T 1C -Pcoverage,all-test
- mvn sonar:sonar -Dsonar.projectKey=Valaragen_USAR-GIS
